name: Build RavenSMS Android App

on:
  release:
    types: [created]

defaults:
  run:
    shell: bash
    working-directory: src/SmsDeliveryChannels/SMS.Net.RavenSMS/Clients/SMS.Net.RavenSMS.Client.Ionic

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Build Ionic App
        run: ionic build

      - name: Copy Android
        run: ionic capacitor copy android

      - name: Build Android Dev APK
        run: ionic capacitor build android

      - name: Build Android Release APK
        run: ionic capacitor build android --release --prod

      - name: Generate the Android App Bundle
        run: |
          cd ./android
          chmod +x ./gradlew
          ./gradlew bundle

      - name: Check folder content
        run: |
          cd ./android/app/build/outputs/apk/debug
          ls

      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: app-dev
          path: android/**
